version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - db:mysql
    volumes:
      - .:/go/src/github.com/masashi1014/go_sample
    command: realize start --run --no-config
  db:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.09"
    command:
      ["/cloud_sql_proxy",
      "-instances=mimetic-sweep-245604:asia-east1:cloudsqltest=tcp:0.0.0.0:3306",
      "-credential_file=/config/mimetic-sweep-245604-80ccded9d776.json"]
    volumes:
      - "./config/env/mimetic-sweep-245604-80ccded9d776.json:/config/mimetic-sweep-245604-80ccded9d776.json"
    ports:
      - "3306:3306"
